services:
  mongodb: 
    image: mongodb/mongodb-community-server:7.0.32-rc2-ubi8-slim
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=toor
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: